// Generated by CoffeeScript 1.8.0

/*
 * redis-backups 项目主程序
 * author:YuanXiangDong
 * date: 2015-04-28
 */

(function() {
  var c, config, debuglog, env, fs, os, p, path, pkg, start, _;

  fs = require("fs");

  path = require("path");

  p = require('commander');

  _ = require('underscore');

  debuglog = require("debug")("redis-backups::server");

  os = require("os");

  pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "../package.json")));

  p.version(pkg.version).option('-e, --environment [type]', 'runtime environment of [development, production, testing]', 'development').parse(process.argv);


  /*
   * bootstrap config
   */

  env = p.environment || 'development';

  c = require('./config/config');

  config = require('./config/config')[env];

  config.version = pkg.version;

  config.root = path.resolve(__dirname, "../");

  config.backupPath = path.join(os.tmpdir(), "" + (config.backupDirName || 'development'));

  start = function(config) {
    var backupUtil;
    require('./utils/upload_util').init(config);
    require('./utils/delete_buckup').init(config);
    backupUtil = require('./utils/backup_util');
    backupUtil.init(config);
    backupUtil.start(function(err) {
      var deleteBackup;
      if (err != null) {
        return console.dir(err);
      }
      deleteBackup = require("./utils/delete_buckup");
      deleteBackup.deleteBackup(function(err, stdout) {
        if (err != null) {
          return console.error(err);
        }
        console.log(stdout);
      });
    });
  };

  start(config);

}).call(this);
