// Generated by CoffeeScript 1.8.0
(function() {
  var BACKUP_RDB_PATH, OVER_TIME_SECOND, assert, child_process, dateFormat, debuglog, deleteBackup, fs, init, mkdirp, path, uploadUtil, _;

  _ = require('underscore');

  debuglog = require("debug")("redis-backups::backup_util");

  fs = require("fs");

  path = require("path");

  child_process = require("child_process");

  assert = require("assert");

  dateFormat = require('dateformat');

  mkdirp = require("mkdirp");

  uploadUtil = require('./upload_util');

  BACKUP_RDB_PATH = null;

  OVER_TIME_SECOND = 2592000;

  init = function(config) {
    BACKUP_RDB_PATH = config.backupPath;
    mkdirp.sync(BACKUP_RDB_PATH);
    return OVER_TIME_SECOND = config.overTimeSecond || 2592000;
  };

  deleteBackup = function(callback) {
    var cmd, date, times;
    times = Date.now() - (OVER_TIME_SECOND * 1000);
    date = new Date(times);
    cmd = "rm -r " + BACKUP_RDB_PATH + "/redisBuck_" + (dateFormat(date, "yyyymmddHH")) + "*.tar.gz";
    debuglog("cmd: " + cmd);
    child_process.exec(cmd, function(err, stdout, stderr) {
      return callback(err, stdout);
    });
  };

  module.exports = {
    init: init,
    deleteBackup: deleteBackup
  };

}).call(this);
