// Generated by CoffeeScript 1.8.0
(function() {
  var BUCKUP_DIR, OSS_CLIENT, OssEasy, assert, debuglog, fs, init, path, upload, _;

  _ = require('underscore');

  debuglog = require("debug")("redis-backups::upload_util");

  OssEasy = require("oss-easy");

  fs = require("fs");

  path = require("path");

  assert = require("assert");

  OSS_CLIENT = null;

  BUCKUP_DIR = null;

  init = function(config) {
    if (OSS_CLIENT != null) {
      console.error("[oss_depositer::init] OSS_CLIENT is already inited");
      return;
    }
    OSS_CLIENT = new OssEasy(config.oss);
    return BUCKUP_DIR = config.backupDirName || 'development';
  };

  upload = function(sourceFile, callback) {
    if (!fs.existsSync(sourceFile)) {
      console.error("missing sourceFile: " + sourceFile);
      return;
    }
    OSS_CLIENT.uploadFile(sourceFile, "" + BUCKUP_DIR + "/" + (path.basename(sourceFile)), function(err) {
      if (err != null) {
        console.error("upload_util: upload is error: " + err);
      }
      return callback(err);
    });
  };

  module.exports = {
    init: init,
    upload: upload
  };

}).call(this);
